### ISSUE TITLE
Question on Generating Graphs

### ISSUE THREAD

**Issue by virtual-world-oss** [zhkai/MTSF-DG#2]
I’ve read your paper on dynamic graph modeling for multiple time series forecasting and am interested in learning how to construct dynamic graphs. 
Could you provide the code for generating the ‘adj_hf.pkl’ and ‘adj_mx.pkl’ files, or direct me to their location in your code repository?

**Comment by zhkai** [comment]
I will update the rest codes in time after finishing my papers at hand. I upload the experimental codes for reference.
