### ISSUE TITLE
Questions about the graph

### ISSUE THREAD

**Issue by emmmmmmmmmmmmmmmmmmmmm** [zhkai/MTSF-DG#3]
Thank you very much for sharing your code, very interesting work!
I have read your paper and your code and become confused about the adjacency matrixes used in the code. In the paper, the adjacency matrix is set to be dynamic, but in the code it seems to be fixed. Besides, in the paper the values of the adjacency matrix are set to be 0 or 1, but after printing the preset matrix you provide in 'adj_hf.pkl' file, I find the values are different. How to explain this two questions?
I would appreciate it very much if you could answer my questions. Thanks again!

**Comment by zhkai** [comment]
1. Sorry for this mistake in the paper. The values of the adjacency matrix are the coefficients.
2. I will update the rest codes in time after finishing my papers at hand. I upload the experimental codes for reference.
