### ISSUE TITLE
Location for metr-la.h5 data

### ISSUE THREAD

**Issue by Nikita-Acsys** [zhkai/MTSF-DG#4]
Hello,

In the graphlearning.py file, you are reading the data from the following location:

`df = pd.read_hdf('./data/metr-la.h5')`

But I am not able to locate it. Could you please let me know where to find it?

**Comment by zhkai** [comment]
Hi

You can find the datasets at https://github.com/liyaguang/DCRNN?tab=readme-ov-file#data-preparation
